version: '3.8'

services:
  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.container-data/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.container-data/rabbitmq/log/:/var/log/rabbitmq
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      - network

  postgres:
    image: 'postgres:13-alpine'
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: hodor
    volumes:
      - ~/.container-data/postgres/data/:/var/lib/postgresql/data

  pgadmin:
    image: 'dpage/pgadmin4'
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: jakub.godawa@punktalab.eu
      PGADMIN_DEFAULT_PASSWORD: hodor

  mariadb:
    image: 'mariadb:10.3'
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: hodor

  phpmyadmin:
    image: 'phpmyadmin'
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1

  redis:
    image: 'redis:6.0-alpine'
    restart: always
    ports:
      - 6379:6379

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  container-data:
networks:
  network: {}

